# Generated by Django 3.1.5 on 2021-01-17 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=100000)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 1, 17, 14, 58, 22, 874469, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 1, 17, 14, 58, 22, 875470, tzinfo=utc))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
