# Generated by Django 3.1.5 on 2021-01-17 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210117_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 19, 57, 4, 895696, tzinfo=utc), verbose_name='publishing date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 19, 57, 4, 894694, tzinfo=utc), verbose_name='publishing date'),
        ),
    ]
