# Generated by Django 3.1.5 on 2021-01-19 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210118_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 12, 50, 29, 374835, tzinfo=utc), verbose_name='publishing date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 12, 50, 29, 374835, tzinfo=utc), verbose_name='publishing date'),
        ),
    ]
